name: Remote Access Setup
on: [workflow_dispatch]

jobs:
  macos-rdp:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - name: Configure Remote Management
      run: |
        # Enable Remote Management with full privileges
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on \
          -privs -all -users runner \
          -clientopts -setmenuextra -menuextra yes -restart -agent -console

    - name: Setup Network Access
      run: |
        # Allow ARDAgent through firewall
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
          --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
          --unblock /System/Library/CoreServices/RemoteManagement/ARDAgent.app

        # Open VNC port using packet filter
        echo "pass in proto tcp from any to any port 5900" | sudo pfctl -ef -

    - name: Configure System User
      run: |
        # Create admin user with secure token
        if ! id -u runner >/dev/null 2>&1; then
          sudo dscl . -create /Users/runner
          sudo dscl . -create /Users/runner UserShell /bin/bash
          sudo dscl . -create /Users/runner RealName "CI Runner"
          sudo dscl . -create /Users/runner UniqueID "201"
          sudo dscl . -create /Users/runner PrimaryGroupID "80"
          sudo dscl . -create /Users/runner NFSHomeDirectory /Users/runner
          sudo mkdir /Users/runner
          sudo chown runner:staff /Users/runner

          # Set password and secure token
          echo "P@ssw0rd!" | sudo dscl . -passwd /Users/runner
          sudo sysadminctl -adminUser "$(whoami)" -adminPassword "" \
            -secureTokenOn runner -password "P@ssw0rd!"
        else
          # Reset existing user
          echo "P@ssw0rd!" | sudo dscl . -passwd /Users/runner
          sudo sysadminctl -adminUser "$(whoami)" -adminPassword "" \
            -resetPasswordFor runner -newPassword "P@ssw0rd!"
        fi

        # Add to admin groups
        sudo dseditgroup -o edit -a runner -t user admin
        sudo dseditgroup -o edit -a runner -t user com.apple.access_remote-desktop
        sudo dseditgroup -o edit -a runner -t user com.apple.access_ssh

    - name: Setup Ngrok Tunnel
      run: |
        # Install and configure ngrok
        curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
        unzip ngrok-v3-stable-darwin-amd64.zip
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok tcp 5900 >/dev/null 2>&1 &

    - name: Verification Steps
      run: |
        # Verify remote services
        sudo systemsetup -getremotelogin
        sudo systemsetup -getremoteappleevents

        # List firewall rules
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --listapps

        # Display connection info
        echo "VNC Connection String:"
        curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
        echo "Username: runner"
        echo "Password: P@ssw0rd!"
