name: winrdp
on: [push, workflow_dispatch]
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Download ngrok
      run: |
        curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
        unzip ngrok-v3-stable-darwin-amd64.zip
    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Screen Sharing
      run: |
        sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -allUsers -privs -all -clientopts -setmenuextra -menuextra yes
    - name: Configure firewall
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --addport 5900 --tcp
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app
    - name: Set user password
      run: echo "runner:P@ssw0rd!" | sudo chpasswd
    - name: Start ngrok tunnel
      run: ./ngrok tcp 5900
