name: winrdp
on: [push, workflow_dispatch]
jobs:
 macos:
  runs-on: macos-latest
  steps:
  - name: Download ngrok
    run: |
      curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
      unzip ngrok-v3-stable-darwin-amd64.zip
      
  - name: Authenticate ngrok
    run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

  - name: Enable Screen Sharing
    run: |
      sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
        -activate -configure -access -on \
        -privs -all -users runner

  - name: Configure firewall
    run: |
      sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
        --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app

  - name: Ensure user exists and set password
    run: |
      if ! id -u runner &>/dev/null; then
        sudo sysadminctl -addUser runner -password "P@ssw0rd!" -admin
      else
        echo "runner:P@ssw0rd!" | sudo chpasswd
      fi

  - name: Start ngrok tunnel
    run: ./ngrok tcp 5900
