name: winrdp
on: [push, workflow_dispatch]
jobs:
 macos:
  runs-on: macos-latest
  steps:
  - name: Download ngrok
    run: |
      curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
      unzip ngrok-v3-stable-darwin-amd64.zip

  - name: Authenticate ngrok
    run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

  - name: Enable Remote Management
    run: |
      # Full activation with security bypass
      sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
        -activate -configure -access -on \
        -privs -all -users runner \
        -clientopts -setmenuextra -menuextra yes

  - name: Configure firewall settings
    run: |
      # Allow ARDAgent through firewall
      sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
        --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app
      sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
        --unblock /System/Library/CoreServices/RemoteManagement/ARDAgent.app

      # Open VNC port directly
      sudo pfctl -a com.apple/250.ApplicationFirewall -Ef - <<EOF
      pass in proto tcp from any to any port 5900
      EOF

  - name: Manage user account
    run: |
      # Create or reset user without password prompt
      if ! id -u runner >/dev/null 2>&1; then
        sudo sysadminctl -addUser runner -password "P@ssw0rd!" -admin
      else
        sudo sysadminctl -resetPasswordFor "runner" -newPassword "P@ssw0rd!"
      fi

      # Ensure user is in appropriate groups
      sudo dseditgroup -o edit -a runner -t user com.apple.access_ssh
      sudo dseditgroup -o edit -a runner -t user com.apple.access_remote-desktop

  - name: Start ngrok tunnel
    run: ./ngrok tcp 5900
