name: winrdp
on: [push, workflow_dispatch]
jobs:
 macos:
  runs-on: macos-latest
  steps:
  - name: Download ngrok
    run: |
      curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
      unzip ngrok-v3-stable-darwin-amd64.zip
  - name: Authenticate ngrok
    run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
  - name: Enable Screen Sharing
    run: |
      # Enable Remote Management
      sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
        -activate -configure -access -on \
        -privs -all -users runner
  - name: Configure firewall
    run: |
      # Allow VNC connections
      sudo /usr/libexec/ApplicationFirewall/socketfilterfw \
        --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app
      sudo pfctl -a com.apple/250.ApplicationFirewall -E
  - name: Set user password
    run: |
      sudo sysadminctl -addUser runner -password "P@ssw0rd!"
      sudo dscl . -passwd /Users/runner "P@ssw0rd!"
  - name: Start ngrok tunnel
    run: ./ngrok tcp 5900
